-- MySQL Script generated by MySQL Workbench
-- 04/12/16 08:01:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zodream
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zodream
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zodream` DEFAULT CHARACTER SET utf8 ;
USE `zodream` ;

-- -----------------------------------------------------
-- Table `zodream`.`zd_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_user` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '用户表主键Id 用户表',
  `name` VARCHAR(30) NOT NULL COMMENT '用户名',
  `email` VARCHAR(100) NOT NULL COMMENT '邮箱',
  `password` VARCHAR(64) NOT NULL COMMENT '密码',
  `token` VARCHAR(60) NULL COMMENT '自动登陆的认证码',
  `login_num` INT(10) NULL DEFAULT 1 COMMENT '登录次数',
  `update_ip` VARCHAR(20) NULL COMMENT '最近登录IP',
  `update_at` INT(10) NULL COMMENT '最近登录时间',
  `previous_ip` VARCHAR(20) NULL COMMENT '上一次登录ip',
  `previous_at` INT(10) NULL COMMENT '上一次登录时间',
  `create_ip` VARCHAR(20) NULL,
  `create_at` INT(10) NULL COMMENT '注册时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_role` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '角色的主键 角色表',
  `name` VARCHAR(45) NOT NULL COMMENT '角色名',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_authorization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_authorization` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '权限主键 权限表',
  `name` VARCHAR(45) NOT NULL COMMENT '权限名',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_role_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_role_user` (
  `user_id` INT(10) NOT NULL COMMENT '用户id 用户与角色关联表',
  `role_id` INT(10) NOT NULL COMMENT '角色id',
  INDEX `fk_user_idx` (`user_id` ASC),
  INDEX `fk_role_idx` (`role_id` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zodream`.`zd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `zodream`.`zd_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_authorization_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_authorization_role` (
  `role_id` INT(10) NOT NULL COMMENT '权限 与角色关联表',
  `authorization_id` INT(10) NOT NULL,
  INDEX `fk_role_idx` (`role_id` ASC),
  INDEX `fk_authorization_idx` (`authorization_id` ASC),
  CONSTRAINT `fk_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `zodream`.`zd_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_authorization`
    FOREIGN KEY (`authorization_id`)
    REFERENCES `zodream`.`zd_authorization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_log` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '日志表',
  `ip` VARCHAR(20) NOT NULL,
  `url` VARCHAR(255) NULL,
  `user` VARCHAR(30) NOT NULL COMMENT '用户名',
  `event` VARCHAR(20) NOT NULL COMMENT '事件',
  `data` TEXT NULL COMMENT '事件的详细情况',
  `create_at` INT(10) NOT NULL COMMENT '发生时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_login_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_login_log` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '登陆日志表',
  `ip` VARCHAR(20) NOT NULL,
  `user` VARCHAR(45) NOT NULL COMMENT '用户名',
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '用户登录的状态 成功或失败',
  `mode` VARCHAR(45) NULL COMMENT '登录的方式',
  `create_at` INT(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_tree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_tree` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '无限树菜单表',
  `name` VARCHAR(45) NOT NULL COMMENT '标题名',
  `url` VARCHAR(45) NULL COMMENT '所代表的网址',
  `left` INT(10) NULL COMMENT '左值',
  `right` INT(10) NULL COMMENT '右值',
  `parent_id` INT(10) NULL DEFAULT 0,
  `level` INT(10) NULL DEFAULT 0 COMMENT '水平深度',
  `position` INT(10) NULL DEFAULT 0 COMMENT '位置，顺序',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_navigation_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_navigation_category` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '首页导航链接分类表',
  `name` VARCHAR(20) NOT NULL COMMENT '导航分类的类名',
  `position` INT(10) NULL DEFAULT 0 COMMENT '排放顺序',
  `user_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`user_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zodream`.`zd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_navigation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_navigation` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '首页导航链接表',
  `name` VARCHAR(100) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `catagory_id` INT(10) NOT NULL,
  `position` INT(10) NULL DEFAULT 0,
  `user_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`user_id` ASC),
  INDEX `fk_catagory_idx` (`catagory_id` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zodream`.`zd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_catagory`
    FOREIGN KEY (`catagory_id`)
    REFERENCES `zodream`.`zd_navigation_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_talk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_talk` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '网站发展历程表',
  `content` VARCHAR(255) NOT NULL COMMENT '个人说说的内容',
  `user_id` INT(10) NOT NULL,
  `create_at` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zodream`.`zd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_post` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '博客表',
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `user_id` INT(10) NOT NULL,
  `update_at` INT(10) NULL,
  `create_at` INT(10) NULL,
  `excerpt` TEXT NULL COMMENT '摘录，节选',
  `status` VARCHAR(20) NULL DEFAULT 'publish' COMMENT '发布的状态',
  `comment_status` VARCHAR(20) NULL DEFAULT 'open' COMMENT '评论的状态，是否可以评论',
  `ping_status` VARCHAR(20) NULL DEFAULT 'open',
  `password` VARCHAR(20) NULL COMMENT '密码',
  `name` VARCHAR(200) NULL,
  `to_ping` TEXT NULL,
  `pinged` TEXT NULL,
  `parent` INT(10) NULL DEFAULT 0,
  `guid` VARCHAR(255) NULL COMMENT '固定链接',
  `position` INT(10) NULL DEFAULT 0,
  `type` VARCHAR(20) NULL DEFAULT 'post',
  `mime_type` VARCHAR(20) NULL,
  `comment_count` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zodream`.`zd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_comment` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '博客评论表',
  `comment` TEXT NOT NULL,
  `author` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `url` VARCHAR(200) NULL,
  `ip` VARCHAR(20) NULL,
  `create_at` INT(10) NULL,
  `karma` INT(11) NULL DEFAULT 0,
  `approved` VARCHAR(20) NULL DEFAULT '1',
  `agent` VARCHAR(255) NULL,
  `type` VARCHAR(20) NULL,
  `comment_parent` INT(20) NULL DEFAULT 0,
  `user_id` INT(10) NULL DEFAULT 0,
  `post_id` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_idx` (`post_id` ASC),
  CONSTRAINT `fk_post`
    FOREIGN KEY (`post_id`)
    REFERENCES `zodream`.`zd_post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_commentmeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_commentmeta` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '博客评论拓展表',
  `comment_id` INT(10) NOT NULL,
  `name` VARCHAR(255) NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_idx` (`comment_id` ASC),
  CONSTRAINT `fk_comment`
    FOREIGN KEY (`comment_id`)
    REFERENCES `zodream`.`zd_comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_postmeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_postmeta` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '博客拓展表',
  `post_id` INT(10) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_idx` (`post_id` ASC),
  CONSTRAINT `fk_post`
    FOREIGN KEY (`post_id`)
    REFERENCES `zodream`.`zd_post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_option` (
  `name` VARCHAR(255) NOT NULL COMMENT '变量名 设置表',
  `value` TEXT NULL,
  `autoload` VARCHAR(20) NULL DEFAULT 'yes',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_term`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_term` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '博客分类表',
  `name` VARCHAR(200) NOT NULL,
  `slug` VARCHAR(200) NULL,
  `group` INT(10) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_termmeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_termmeta` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '博客分类拓展表',
  `term_id` INT(10) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_term_idx` (`term_id` ASC),
  CONSTRAINT `fk_term`
    FOREIGN KEY (`term_id`)
    REFERENCES `zodream`.`zd_term` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_term_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_term_post` (
  `post_id` INT(10) NOT NULL COMMENT '博客与分类关联表',
  `term_id` INT(10) NOT NULL,
  `position` INT(10) NULL DEFAULT 0,
  INDEX `fk_post_idx` (`post_id` ASC),
  INDEX `fk_term_idx` (`term_id` ASC),
  CONSTRAINT `fk_post`
    FOREIGN KEY (`post_id`)
    REFERENCES `zodream`.`zd_post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_term`
    FOREIGN KEY (`term_id`)
    REFERENCES `zodream`.`zd_term` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_term_taxonomy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_term_taxonomy` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '分类系统表',
  `term_id` INT(10) NOT NULL,
  `taxonomy` VARCHAR(32) NOT NULL,
  `description` TEXT NULL,
  `parent` INT(10) NULL DEFAULT 0,
  `count` INT(10) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_term_idx` (`term_id` ASC),
  CONSTRAINT `fk_term`
    FOREIGN KEY (`term_id`)
    REFERENCES `zodream`.`zd_term` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_friendlink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_friendlink` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '友情链接表',
  `position` INT(3) NULL DEFAULT 0 COMMENT ' 显示顺序，正序',
  `name` VARCHAR(100) NULL COMMENT '名称',
  `url` VARCHAR(255) NULL COMMENT '网址',
  `description` TEXT NULL COMMENT '解释说明',
  `logo` VARCHAR(255) NULL,
  `type` INT(3) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_forum` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '论坛id 论坛版块表',
  `parent` INT(10) NULL DEFAULT 0 COMMENT '上级论坛id',
  `type` ENUM('group', 'forum', 'sub') NULL DEFAULT 'forum' COMMENT ' 类型 (group:分类 forum:普通论坛 sub:子论坛)',
  `name` VARCHAR(50) NOT NULL COMMENT '名称',
  `status` TINYINT(1) NULL DEFAULT 0 COMMENT ' 显示状态 (0:隐藏 1:正常 3:群组)',
  `position` INT(10) NULL DEFAULT 0 COMMENT '显示顺序',
  `threads` INT(10) NULL DEFAULT 0 COMMENT '主题数量',
  `todaypost` INT(10) NULL DEFAULT 0 COMMENT '今日发帖数量',
  `posts` INT(10) NULL DEFAULT 0 COMMENT ' 帖子数量',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_thread`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_thread` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '主题id 论坛主题表',
  `forum_id` INT(10) NOT NULL COMMENT '上级论坛',
  `title` VARCHAR(100) NOT NULL,
  `readperm` INT(3) NULL DEFAULT 0 COMMENT ' 阅读权限',
  `user_id` INT(10) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `replies` INT(10) NULL DEFAULT 0 COMMENT '回复次数',
  `views` INT(10) NULL DEFAULT 0 COMMENT '浏览次数',
  `update_at` INT(10) NULL COMMENT '最后发表时间',
  `update_user` INT(10) NULL COMMENT ' 最后发表人id',
  `create_at` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`user_id` ASC),
  INDEX `fk_user_name_idx` (`user_name` ASC),
  INDEX `fk_forum_idx` (`forum_id` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zodream`.`zd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_name`
    FOREIGN KEY (`user_name`)
    REFERENCES `zodream`.`zd_user` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forum`
    FOREIGN KEY (`forum_id`)
    REFERENCES `zodream`.`zd_forum` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_thread_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_thread_post` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT ' 帖子id 论坛帖子表',
  `forum_id` INT(10) NOT NULL COMMENT ' 论坛id',
  `thread_id` INT(10) NOT NULL COMMENT '主题id',
  `content` TEXT NOT NULL COMMENT '内容',
  `first` TINYINT(1) NULL DEFAULT 0 COMMENT '是否是首贴 及主题的一楼内容',
  `user_id` INT(10) NOT NULL,
  `user_name` VARCHAR(30) NOT NULL,
  `ip` VARCHAR(20) NULL,
  `create_at` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`user_id` ASC),
  INDEX `fk_user_name_idx` (`user_name` ASC),
  INDEX `fk_forum_idx` (`forum_id` ASC),
  INDEX `fk_thread_idx` (`thread_id` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zodream`.`zd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_name`
    FOREIGN KEY (`user_name`)
    REFERENCES `zodream`.`zd_user` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forum`
    FOREIGN KEY (`forum_id`)
    REFERENCES `zodream`.`zd_forum` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thread`
    FOREIGN KEY (`thread_id`)
    REFERENCES `zodream`.`zd_thread` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_visit` (
  `ip` INT(10) NOT NULL DEFAULT 0 COMMENT '用户IP 浏览记录表',
  `view` INT(10) NOT NULL DEFAULT 0 COMMENT '访问次数')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_moderator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_moderator` (
  `forum_id` INT(10) NOT NULL COMMENT '论坛id 版主表',
  `user_id` INT(10) NOT NULL COMMENT '会员id , 版主表',
  `position` INT(3) NULL DEFAULT 0,
  INDEX `fk_forum_idx` (`forum_id` ASC),
  INDEX `fk_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_forum`
    FOREIGN KEY (`forum_id`)
    REFERENCES `zodream`.`zd_forum` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zodream`.`zd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
