-- MySQL Script generated by MySQL Workbench
-- 05/01/16 10:16:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zodream
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zodream
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zodream` DEFAULT CHARACTER SET utf8 ;
USE `zodream` ;

-- -----------------------------------------------------
-- Table `zodream`.`zd_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_user` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '用户表主键Id 用户表',
  `name` VARCHAR(30) NOT NULL COMMENT '用户名',
  `email` VARCHAR(100) NOT NULL COMMENT '邮箱',
  `password` VARCHAR(64) NOT NULL COMMENT '密码',
  `token` VARCHAR(60) NULL COMMENT '自动登陆的认证码',
  `login_num` INT(10) NULL DEFAULT 0 COMMENT '登录次数',
  `update_ip` VARCHAR(20) NULL COMMENT '最近登录IP',
  `update_at` INT(10) NULL COMMENT '最近登录时间',
  `previous_ip` VARCHAR(20) NULL COMMENT '上一次登录ip',
  `previous_at` INT(10) NULL COMMENT '上一次登录时间',
  `create_ip` VARCHAR(20) NULL,
  `create_at` INT(10) NULL COMMENT '注册时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_role` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '角色的主键 角色表',
  `name` VARCHAR(45) NOT NULL COMMENT '角色名',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_authorization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_authorization` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '权限主键 权限表',
  `name` VARCHAR(45) NOT NULL COMMENT '权限名',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_role_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_role_user` (
  `user_id` INT(10) NOT NULL COMMENT '用户id 用户与角色关联表',
  `role_id` INT(10) NOT NULL COMMENT '角色id',
  INDEX `fk_user_idx` (`user_id` ASC),
  INDEX `fk_role_idx` (`role_id` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zodream`.`zd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `zodream`.`zd_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_authorization_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_authorization_role` (
  `role_id` INT(10) NOT NULL COMMENT '权限 与角色关联表',
  `authorization_id` INT(10) NOT NULL,
  INDEX `fk_role_idx` (`role_id` ASC),
  INDEX `fk_authorization_idx` (`authorization_id` ASC),
  CONSTRAINT `fk_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `zodream`.`zd_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_authorization`
    FOREIGN KEY (`authorization_id`)
    REFERENCES `zodream`.`zd_authorization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_log` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '日志表',
  `ip` VARCHAR(20) NOT NULL,
  `url` VARCHAR(255) NULL,
  `user` VARCHAR(30) NOT NULL COMMENT '用户名',
  `event` VARCHAR(20) NOT NULL COMMENT '事件',
  `data` TEXT NULL COMMENT '事件的详细情况',
  `create_at` INT(10) NOT NULL COMMENT '发生时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_login_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_login_log` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '登陆日志表',
  `ip` VARCHAR(20) NOT NULL,
  `user` VARCHAR(45) NOT NULL COMMENT '用户名',
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '用户登录的状态 成功或失败',
  `mode` VARCHAR(45) NULL COMMENT '登录的方式',
  `create_at` INT(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_tree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_tree` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '无限树菜单表',
  `name` VARCHAR(45) NOT NULL COMMENT '标题名',
  `url` VARCHAR(45) NULL COMMENT '所代表的网址',
  `left` INT(10) NULL COMMENT '左值',
  `right` INT(10) NULL COMMENT '右值',
  `parent_id` INT(10) NULL DEFAULT 0,
  `level` INT(10) NULL DEFAULT 0 COMMENT '水平深度',
  `position` INT(10) NULL DEFAULT 0 COMMENT '位置，顺序',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_navigation_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_navigation_category` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '首页导航链接分类表',
  `name` VARCHAR(20) NOT NULL COMMENT '导航分类的类名',
  `position` INT(10) NULL DEFAULT 0 COMMENT '排放顺序',
  `user_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`user_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zodream`.`zd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_navigation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_navigation` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '首页导航链接表',
  `name` VARCHAR(100) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `category_id` INT(10) NOT NULL,
  `position` INT(10) NULL DEFAULT 0,
  `user_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`user_id` ASC),
  INDEX `fk_catagory_idx` (`category_id` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zodream`.`zd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_catagory`
    FOREIGN KEY (`category_id`)
    REFERENCES `zodream`.`zd_navigation_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_talk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_talk` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '网站发展历程表',
  `content` VARCHAR(255) NOT NULL COMMENT '个人说说的内容',
  `user_id` INT(10) NOT NULL,
  `create_at` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zodream`.`zd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_post` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '博客表',
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `user_id` INT(10) NOT NULL,
  `update_at` INT(10) NULL,
  `create_at` INT(10) NULL,
  `excerpt` TEXT NULL COMMENT '摘录，节选',
  `status` VARCHAR(20) NULL DEFAULT 'publish' COMMENT '发布的状态',
  `comment_status` VARCHAR(20) NULL DEFAULT 'open' COMMENT '评论的状态，是否可以评论',
  `ping_status` VARCHAR(20) NULL DEFAULT 'open',
  `password` VARCHAR(20) NULL COMMENT '密码',
  `name` VARCHAR(200) NULL,
  `to_ping` TEXT NULL,
  `pinged` TEXT NULL,
  `parent` INT(10) NULL DEFAULT 0,
  `guid` VARCHAR(255) NULL COMMENT '固定链接',
  `position` INT(10) NULL DEFAULT 0,
  `type` VARCHAR(20) NULL DEFAULT 'post' COMMENT 'post文章 page 页面',
  `mime_type` VARCHAR(20) NULL,
  `comment_count` INT(10) NULL DEFAULT 0,
  `recommend` INT(10) NULL DEFAULT 0 COMMENT '推荐数',
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zodream`.`zd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_comment` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '博客评论表',
  `content` TEXT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `url` VARCHAR(200) NULL,
  `ip` VARCHAR(20) NULL,
  `create_at` INT(10) NULL,
  `karma` INT(11) NULL DEFAULT 0,
  `approved` VARCHAR(20) NULL DEFAULT '1' COMMENT '评论是否被批准',
  `agent` VARCHAR(255) NULL COMMENT '评论者的USER AGENT',
  `type` VARCHAR(20) NULL COMMENT '评论类型(pingback/普通)',
  `parent` INT(20) NULL DEFAULT 0 COMMENT '回复',
  `user_id` INT(10) NULL DEFAULT 0,
  `post_id` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_idx` (`post_id` ASC),
  CONSTRAINT `fk_post`
    FOREIGN KEY (`post_id`)
    REFERENCES `zodream`.`zd_post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_commentmeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_commentmeta` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '博客评论拓展表',
  `comment_id` INT(10) NOT NULL,
  `name` VARCHAR(255) NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_idx` (`comment_id` ASC),
  CONSTRAINT `fk_comment`
    FOREIGN KEY (`comment_id`)
    REFERENCES `zodream`.`zd_comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_postmeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_postmeta` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '博客拓展表',
  `post_id` INT(10) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_idx` (`post_id` ASC),
  CONSTRAINT `fk_post`
    FOREIGN KEY (`post_id`)
    REFERENCES `zodream`.`zd_post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_option` (
  `name` VARCHAR(255) NOT NULL COMMENT '变量名 设置表',
  `value` TEXT NOT NULL,
  `autoload` VARCHAR(20) NULL DEFAULT 'yes',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_term`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_term` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '博客分类表',
  `name` VARCHAR(200) NOT NULL,
  `slug` VARCHAR(200) NULL COMMENT '固定链接中的别名 缩略名',
  `group` INT(10) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_termmeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_termmeta` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '博客分类拓展表',
  `term_id` INT(10) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_term_idx` (`term_id` ASC),
  CONSTRAINT `fk_term`
    FOREIGN KEY (`term_id`)
    REFERENCES `zodream`.`zd_term` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_term_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_term_post` (
  `post_id` INT(10) NOT NULL COMMENT '博客与分类关联表',
  `term_id` INT(10) NOT NULL,
  `position` INT(10) NULL DEFAULT 0,
  INDEX `fk_post_idx` (`post_id` ASC),
  INDEX `fk_term_idx` (`term_id` ASC),
  UNIQUE INDEX `post_id_UNIQUE` (`post_id` ASC),
  CONSTRAINT `fk_post`
    FOREIGN KEY (`post_id`)
    REFERENCES `zodream`.`zd_post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_term`
    FOREIGN KEY (`term_id`)
    REFERENCES `zodream`.`zd_term` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_term_taxonomy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_term_taxonomy` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '分类系统表',
  `term_id` INT(10) NOT NULL,
  `taxonomy` VARCHAR(32) NOT NULL COMMENT '分类的类型 \ncategory 分类\ntag 标签',
  `description` TEXT NULL,
  `parent` INT(10) NULL DEFAULT 0,
  `count` INT(10) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_term_idx` (`term_id` ASC),
  CONSTRAINT `fk_term`
    FOREIGN KEY (`term_id`)
    REFERENCES `zodream`.`zd_term` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_friendlink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_friendlink` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '友情链接表',
  `position` INT(3) NULL DEFAULT 0 COMMENT ' 显示顺序，正序',
  `name` VARCHAR(100) NULL COMMENT '名称',
  `url` VARCHAR(255) NULL COMMENT '网址',
  `description` TEXT NULL COMMENT '解释说明',
  `logo` VARCHAR(255) NULL,
  `type` INT(3) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_forum` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '论坛id 论坛版块表',
  `parent` INT(10) NULL DEFAULT 0 COMMENT '上级论坛id',
  `type` ENUM('group', 'forum', 'sub') NULL DEFAULT 'forum' COMMENT ' 类型 (group:分类 forum:普通论坛 sub:子论坛)',
  `name` VARCHAR(50) NOT NULL COMMENT '名称',
  `status` TINYINT(1) NULL DEFAULT 0 COMMENT ' 显示状态 (0:隐藏 1:正常 3:群组)',
  `position` INT(10) NULL DEFAULT 0 COMMENT '显示顺序',
  `threads` INT(10) NULL DEFAULT 0 COMMENT '主题数量',
  `todaypost` INT(10) NULL DEFAULT 0 COMMENT '今日发帖数量',
  `posts` INT(10) NULL DEFAULT 0 COMMENT ' 帖子数量',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_thread`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_thread` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '主题id 论坛主题表',
  `forum_id` INT(10) NOT NULL COMMENT '上级论坛',
  `title` VARCHAR(100) NOT NULL,
  `readperm` INT(3) NULL DEFAULT 0 COMMENT ' 阅读权限',
  `user_id` INT(10) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `replies` INT(10) NULL DEFAULT 0 COMMENT '回复次数',
  `views` INT(10) NULL DEFAULT 0 COMMENT '浏览次数',
  `update_at` INT(10) NULL COMMENT '最后发表时间',
  `update_user` INT(10) NULL COMMENT ' 最后发表人id',
  `create_at` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`user_id` ASC),
  INDEX `fk_user_name_idx` (`user_name` ASC),
  INDEX `fk_forum_idx` (`forum_id` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zodream`.`zd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_name`
    FOREIGN KEY (`user_name`)
    REFERENCES `zodream`.`zd_user` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forum`
    FOREIGN KEY (`forum_id`)
    REFERENCES `zodream`.`zd_forum` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_thread_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_thread_post` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT ' 帖子id 论坛帖子表',
  `forum_id` INT(10) NOT NULL COMMENT ' 论坛id',
  `thread_id` INT(10) NOT NULL COMMENT '主题id',
  `content` TEXT NOT NULL COMMENT '内容',
  `first` TINYINT(1) NULL DEFAULT 0 COMMENT '是否是首贴 及主题的一楼内容',
  `user_id` INT(10) NOT NULL,
  `user_name` VARCHAR(30) NOT NULL,
  `ip` VARCHAR(20) NULL,
  `create_at` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`user_id` ASC),
  INDEX `fk_user_name_idx` (`user_name` ASC),
  INDEX `fk_forum_idx` (`forum_id` ASC),
  INDEX `fk_thread_idx` (`thread_id` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zodream`.`zd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_name`
    FOREIGN KEY (`user_name`)
    REFERENCES `zodream`.`zd_user` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forum`
    FOREIGN KEY (`forum_id`)
    REFERENCES `zodream`.`zd_forum` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thread`
    FOREIGN KEY (`thread_id`)
    REFERENCES `zodream`.`zd_thread` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_visit` (
  `ip` INT(10) NOT NULL DEFAULT 0 COMMENT '用户IP 浏览记录表',
  `view` INT(10) NOT NULL DEFAULT 0 COMMENT '访问次数')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_moderator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_moderator` (
  `forum_id` INT(10) NOT NULL COMMENT '论坛id 版主表',
  `user_id` INT(10) NOT NULL COMMENT '会员id , 版主表',
  `position` INT(3) NULL DEFAULT 0,
  INDEX `fk_forum_idx` (`forum_id` ASC),
  INDEX `fk_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_forum`
    FOREIGN KEY (`forum_id`)
    REFERENCES `zodream`.`zd_forum` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `zodream`.`zd_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_wechat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_wechat` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '微信公众账号id',
  `name` VARCHAR(60) NOT NULL COMMENT '公众号名称',
  `original_id` VARCHAR(20) NOT NULL COMMENT '原始id',
  `app_id` VARCHAR(50) NULL COMMENT 'AppId',
  `app_secret` VARCHAR(50) NULL COMMENT 'AppSecret',
  `token` VARCHAR(10) NULL COMMENT '加密token',
  `aes_key` VARCHAR(45) NULL COMMENT 'AES加密key',
  `account` VARCHAR(20) NULL COMMENT '微信号',
  `tag` VARCHAR(20) NULL COMMENT '接口标识',
  `access_token` VARCHAR(30) NULL COMMENT '微信access_token',
  `type` INT(1) NULL DEFAULT 0 COMMENT '类型 0订阅号 1服务号 2企业号',
  `status` TINYINT(1) NULL DEFAULT 0 COMMENT '同步状态 0 未同步 1 素材完成同步',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tag_UNIQUE` (`tag` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_wechat_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_wechat_menu` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `wechat_id` INT(10) NULL COMMENT '所属公众号',
  `parent` INT(10) NULL DEFAULT 0 COMMENT '菜单父id',
  `name` VARCHAR(45) NOT NULL COMMENT '菜单名称',
  `type` ENUM('click', 'view', 'scancode_push', 'scancode_waitmsg', 'pic_sysphoto', 'pic_photo_or_album', 'pic_weixin', 'location_select') NULL DEFAULT 'click' COMMENT '菜单类型',
  `key` VARCHAR(200) NULL COMMENT '菜单触发值',
  `position` INT(10) NULL DEFAULT 0 COMMENT '排序',
  `update_at` INT(10) NULL,
  `create_at` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wechat_idx` (`wechat_id` ASC),
  CONSTRAINT `fk_wechat`
    FOREIGN KEY (`wechat_id`)
    REFERENCES `zodream`.`zd_wechat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_wechat_reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_wechat_reply` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `wechat_id` INT(10) NULL,
  `type` ENUM('follow', 'default', 'keywords') NULL COMMENT '回复类型 follow 关注回复 default 默认回复 keywords 关键词回复',
  `name` VARCHAR(30) NULL COMMENT '规则名称',
  `trigger_keyword` VARCHAR(500) NULL COMMENT '触发文字',
  `trigger_type` ENUM('equal', 'contain') NULL COMMENT '触发条件类型',
  `content` VARCHAR(255) NULL COMMENT '触发内容 events',
  `group_ids` VARCHAR(45) NULL COMMENT '适用范围：组id数组',
  `update_at` INT(10) NULL,
  `create_at` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wechat_idx` (`wechat_id` ASC),
  CONSTRAINT `fk_wechat`
    FOREIGN KEY (`wechat_id`)
    REFERENCES `zodream`.`zd_wechat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_wechat_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_wechat_group` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `wechat_id` INT(10) NULL,
  `parent` INT(10) NULL COMMENT '粉丝组group_id',
  `name` VARCHAR(90) NULL COMMENT '组名',
  `fan_count` INT(10) NULL DEFAULT 0 COMMENT '粉丝数',
  `is_default` TINYINT(1) NULL DEFAULT 1 COMMENT '是否为默认组:1=默认,0=自建',
  `update_at` INT(10) NULL,
  `create_at` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wechat_idx` (`wechat_id` ASC),
  CONSTRAINT `fk_wechat`
    FOREIGN KEY (`wechat_id`)
    REFERENCES `zodream`.`zd_wechat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_wechat_fan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_wechat_fan` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `wechat_id` INT(10) NULL COMMENT '所属公众号',
  `group_id` INT(10) NULL COMMENT '粉丝组group_id',
  `openid` VARCHAR(100) NULL COMMENT 'OPENID',
  `nickname` VARCHAR(300) NULL COMMENT '昵称',
  `signature` VARCHAR(300) NULL COMMENT '签名',
  `remark` TEXT NULL COMMENT '备注',
  `sex` ENUM('女', '男') NULL COMMENT '性别',
  `language` VARCHAR(300) NULL COMMENT '语言',
  `city` VARCHAR(300) NULL COMMENT '城市',
  `province` VARCHAR(300) NULL COMMENT '省',
  `country` VARCHAR(300) NULL COMMENT '国家',
  `avatar` VARCHAR(300) NULL COMMENT '头像',
  `unionid` INT NULL COMMENT 'unionid',
  `liveness` INT(10) NULL COMMENT '用户活跃度',
  `subscribed_at` INT(10) NULL,
  `update_at` INT(10) NULL COMMENT '最后一次在线时间',
  `create_at` INT(10) NULL,
  `deleted_at` INT(10) NULL COMMENT '实现软删除',
  PRIMARY KEY (`id`),
  INDEX `fk_wechat_idx` (`wechat_id` ASC),
  INDEX `fk_group_idx` (`group_id` ASC),
  CONSTRAINT `fk_wechat`
    FOREIGN KEY (`wechat_id`)
    REFERENCES `zodream`.`zd_wechat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group`
    FOREIGN KEY (`group_id`)
    REFERENCES `zodream`.`zd_wechat_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_fan_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_fan_report` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `wechat_id` INT(10) NULL,
  `openid` VARCHAR(100) NULL,
  `type` VARCHAR(100) NULL COMMENT '操作类型',
  `create_at` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wechat_idx` (`wechat_id` ASC),
  CONSTRAINT `fk_wechat`
    FOREIGN KEY (`wechat_id`)
    REFERENCES `zodream`.`zd_wechat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_wechat_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_wechat_event` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `wechat_id` INT(10) NULL,
  `key` VARCHAR(128) NULL COMMENT '事件名称',
  `type` ENUM('addon', 'material') NULL COMMENT '事件类型',
  `value` VARCHAR(30) NULL COMMENT '触发值',
  `create_at` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wechat_idx` (`wechat_id` ASC),
  CONSTRAINT `fk_wechat`
    FOREIGN KEY (`wechat_id`)
    REFERENCES `zodream`.`zd_wechat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_wechat_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_wechat_message` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `wechat_id` INT(10) NULL,
  `fan_id` INT(10) NULL COMMENT '粉丝ID 不存在时为公众号回复',
  `create_at` INT(10) NULL COMMENT '消息发送时间 OR 消息回复时间',
  `resource_id` INT(10) NULL COMMENT '对应消息资源',
  `reply_id` INT(10) NULL DEFAULT 0 COMMENT '消息回复ID',
  `content` TEXT NULL COMMENT '消息内容',
  `msg_id` VARCHAR(25) NULL COMMENT '消息id',
  PRIMARY KEY (`id`),
  INDEX `fk_wechat_idx` (`wechat_id` ASC),
  CONSTRAINT `fk_wechat`
    FOREIGN KEY (`wechat_id`)
    REFERENCES `zodream`.`zd_wechat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_wechat_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_wechat_resource` (
  `id` INT(10) NOT NULL,
  `wechat_id` INT(10) NULL,
  `detail` TEXT NULL COMMENT '详细',
  `type` ENUM('text', 'image', 'voice', 'shortvideo', 'link', 'location') NULL COMMENT '消息类型 text 文字 image 图片 shortvideo 短视频 location 位置',
  `status` TINYINT(1) NULL COMMENT '同步状态 0 未同步 1 已经完成同步',
  `update_at` INT(10) NULL,
  `create_at` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wechat_idx` (`wechat_id` ASC),
  CONSTRAINT `fk_wechat`
    FOREIGN KEY (`wechat_id`)
    REFERENCES `zodream`.`zd_wechat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_wechat_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_wechat_material` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `wechat_id` INT(10) NULL,
  `media_id` VARCHAR(30) NULL COMMENT 'mediaId',
  `original_id` VARCHAR(60) NULL COMMENT '原始微信素材id',
  `parent` INT(10) NULL DEFAULT 0,
  `type` ENUM('article', 'image', 'voice', 'video', 'text') NULL COMMENT '素材类型',
  `is_mutli` TINYINT(1) NULL DEFAULT 0 COMMENT '是否是多图文 0 否 1 是',
  `can_edit` TINYINT(1) NULL DEFAULT 0 COMMENT '是否可编辑 0 不可 1 可编辑',
  `title` VARCHAR(200) NULL COMMENT '标题',
  `descrption` VARCHAR(360) NULL COMMENT '摘要',
  `author` VARCHAR(24) NULL COMMENT '作者',
  `content` TEXT NULL COMMENT '内容',
  `cover_media_id` VARCHAR(100) NULL COMMENT '封面 media_id',
  `cover_url` VARCHAR(100) NULL COMMENT '封面url',
  `show_cover` TINYINT(1) NULL DEFAULT 0 COMMENT '是否显示封面 0 不显示 1 显示',
  `create_from` TINYINT(1) NULL DEFAULT 0 COMMENT '0 微信同步到 1同步到微信',
  `source_url` VARCHAR(100) NULL COMMENT '内容连接资源',
  `content_url` VARCHAR(100) NULL COMMENT '原文链接',
  `create_at` INT(10) NULL,
  `update_at` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wechat_idx` (`wechat_id` ASC),
  CONSTRAINT `fk_wechat`
    FOREIGN KEY (`wechat_id`)
    REFERENCES `zodream`.`zd_wechat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_model` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '动态表单 id',
  `name` VARCHAR(45) NOT NULL COMMENT '名称',
  `tablename` VARCHAR(45) NOT NULL,
  `categorytpl` VARCHAR(45) NULL COMMENT '首页模板',
  `listtpl` VARCHAR(45) NULL COMMENT '列表模板',
  `showtpl` VARCHAR(45) NULL COMMENT '详情模板',
  `setting` TEXT NULL COMMENT '设置',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zodream`.`zd_model_field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zodream`.`zd_model_field` (
  `id` INT(10) NOT NULL COMMENT '动态表单属性',
  `model_id` INT(10) NOT NULL,
  `field` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `length` INT(10) NULL,
  `formtype` VARCHAR(45) NULL,
  `setting` TEXT NULL,
  `position` INT(10) NULL COMMENT '排列顺序',
  `tips` VARCHAR(255) NULL COMMENT '提示',
  `pattern` VARCHAR(45) NULL COMMENT '正则匹配',
  PRIMARY KEY (`id`),
  INDEX `fk_model_idx` (`model_id` ASC),
  CONSTRAINT `fk_model`
    FOREIGN KEY (`model_id`)
    REFERENCES `zodream`.`zd_model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
