<div>管理信息</div>
<ul>
    <li>新闻中心
        <ul>
            <li data="news">国内新闻</li>
            <li>国际新闻</li>
            <li>娱乐新闻</li>
            <li>体育新闻</li>
        </ul>
    </li>
    <li>下载中心
        <ul>
            <li>系统软件</li>
            <li>网络工具</li>
            <li>安全相关</li>
            <li>媒体工具</li>
        </ul>
    </li>
    <li>影视频道
        <ul>
            <li>动作片</li>
            <li>爱情片</li>
            <li>喜剧片</li>
            <li>连续剧</li>
        </ul>
    </li>
    <li>网上商城
        <ul>
            <li>手机数码</li>
            <li>家用电器</li>
            <li>品牌电脑</li>
            <li>图书杂志</li>
        </ul>
    </li>
    <li>FLASH频道
        <ul>
            <li>游戏</li>
            <li>音乐MV</li>
        </ul>
    </li>
    <li>图片频道
        <ul>
            <li>明星风采</li>
            <li>自然风景</li>
            <li>动漫图片</li>
        </ul>
    </li>
    <li>文章中心
        <ul>
            <li>小说</li>
            <li>散文</li>
            <li>诗歌</li>
        </ul>
    </li>
    <li>分类信息
        <ul>
            <li>房屋信息
                <ul>
                    <li>房屋求租</li>
                    <li>房屋出租</li>
                    <li>房屋求购</li>
                    <li>房屋出售</li>
                    <li>办公用房</li>
                    <li>旺铺门面</li>
                </ul>
            </li>
            <li>跳蚤市场
                <ul>
                    <li>电脑配件</li>
                    <li>电器数码</li>
                    <li>通讯产品</li>
                    <li>居家用品</li>
                </ul>
            </li>
            <li>同城生活
                <ul>
                    <li>本地新闻</li>
                    <li>购物打折</li>
                    <li>旅游活动</li>
                    <li>便民告示</li>
                </ul>
            </li>
            <li>求职招聘
                <ul>
                    <li>工程技术</li>
                    <li>财务会计</li>
                    <li>餐饮行业</li>
                    <li>经营管理</li>
                </ul>
            </li>
        </ul>
    </li>
</ul>