<div>系统设置</div>
<ul>
    <li>系统设置
        <ul>
            <li data="option">系统参数设置</li>
            <li>伪静态参数设置</li>
            <li>扩展变量</li>
            <li>安全参数配置</li>
            <li>网站防火墙</li>
        </ul>
    </li>
    <li>数据更新
        <ul>
            <li>数据更新中心</li>
            <li>更新信息页地址</li>
            <li>数据整理</li>
            <li>远程发布</li>
        </ul>
    </li>
    <li>数据表与系统模型
        <ul>
            <li>新建数据表</li>
            <li>管理数据表</li>
        </ul>
    </li>
    <li>计划任务
        <ul>
            <li>管理刷新任务</li>
            <li>管理计划任务</li>
        </ul>
    </li>
    <li>工作流
        <ul>
            <li>增加工作流</li>
            <li>管理工作流</li>
        </ul>
    </li>
    <li>优化方案
        <ul>
            <li>管理优化方案</li>
        </ul>
    </li>
    <li>网站多访问端
        <ul>
            <li>管理网站访问端</li>
        </ul>
    </li>
    <li>扩展菜单
        <ul>
            <li>管理菜单</li>
        </ul>
    </li>
    <li>备份与恢复数据
        <ul>
            <li>备份数据</li>
            <li>恢复数据</li>
            <li>管理备份目录</li>
            <li>执行SQL语句</li>
        </ul>
    </li>
</ul>